services:
  lh-frontend:
    build: ./
    image: base
    working_dir: /usr/src/app/
    environment:
      - 'NEXT_WEBPACK_USEPOLLING=1'
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000
    networks:
      - lh-network
    command: npm run dev
networks:
  lh-network:
    external: true
